CREATE TABLE contacts (
	id INT GENERATED BY DEFAULT AS IDENTITY, /*id SERIAL.*/
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	phone VARCHAR(15), /*This column may accept NULL values.*/
	PRIMARY KEY (id)
);
